### PR TITLE
Multiple changes: external IP, local IP, custom port range flag, etc

### PR DESCRIPTION
**Pull request by muschem**
If curl and wget are both absent (rare, but it happens), dig can also return system external IP

### CODE REVIEW

**Comment by muschem** [comment]
Thought it might be nice to have an option to specify ports, similar to nmap.

**Review by astryzia — APPROVED** [review]
Thanks for adding this! Initially overlooked it because sometimes behind VPNs the dig command won't work. Will merge.

**Review by astryzia — APPROVED** [review]
Very nice changes! Merging.

**Comment by muschem** [comment]
Good point. Wasn't considering a VPN case. Depending on the type of VPN (full vs split-tunnel), I suppose there would be different behavior to consider. Latest commit added telnet and ssh methods as well as the dig option for DNS. Those can be re-ordered however is most effective. I suppose having a completely accurate external IP is just a nice option, since it isn't being used in the scan construction.

**Comment by astryzia** [comment]
I'll add those to the list for future changes. It's probably a good idea to have fall-backs not based purely on what packages are available on the system but to implement checks based on connectivity as well. That way if dig didn't work due to a VPN, it would move to another method to find the external IP. Overall, I know external IP is more informational than necessary in this, but rounded out functionality is good nonetheless :)  Thank you for all these changes! They're great.

**Pull request merged**
